-- Shared dependencies
require("plugins.plenary")
require("plugins.mason")
require("plugins.mini")
require("plugins.fidget")
require("plugins.nvim-dap")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.telescope")

-- All plugins
require("plugins.blink-cmp")
require("plugins.cmake")
require("plugins.conform")
require("plugins.csv")
require("plugins.guess-indent")
require("plugins.image")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.mesone")
require("plugins.neogen")
require("plugins.neogit")
require("plugins.opencode")
require("plugins.render-markdown")
require("plugins.which-key")
require("plugins.toggleterm")

-- Colorscheme
require("plugins.colorscheme")
